# Generated by Django 5.2.4 on 2026-01-15 09:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Article Writing Rules', max_length=200, verbose_name='Title')),
                ('title_uz', models.CharField(default='Article Writing Rules', max_length=200, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(default='Article Writing Rules', max_length=200, null=True, verbose_name='Title')),
                ('title_en', models.CharField(default='Article Writing Rules', max_length=200, null=True, verbose_name='Title')),
                ('content', models.TextField(help_text='Article writing guidelines that authors must accept', verbose_name='Rules Content')),
                ('content_uz', models.TextField(help_text='Article writing guidelines that authors must accept', null=True, verbose_name='Rules Content')),
                ('content_ru', models.TextField(help_text='Article writing guidelines that authors must accept', null=True, verbose_name='Rules Content')),
                ('content_en', models.TextField(help_text='Article writing guidelines that authors must accept', null=True, verbose_name='Rules Content')),
                ('is_active', models.BooleanField(default=True, help_text='Only one set of rules should be active at a time', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Article Rules',
                'verbose_name_plural': 'Article Rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True, verbose_name='email address')),
                ('role', models.CharField(choices=[('READER', "O'quvchi (Reader)"), ('AUTHOR', 'Avtor (Author)')], default='READER', max_length=10, verbose_name='User Role')),
                ('has_accepted_rules', models.BooleanField(default=False, verbose_name='Has Accepted Article Rules')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
