# Generated by Django 5.2.4 on 2026-01-15 15:26

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlerules',
            name='rules_file',
            field=models.FileField(blank=True, help_text='Upload rules as .txt file (optional, max 5MB)', null=True, upload_to=users.models.article_rules_upload_path, validators=[users.models.validate_rules_file], verbose_name='Rules File'),
        ),
        migrations.AlterField(
            model_name='articlerules',
            name='content',
            field=models.TextField(blank=True, help_text='Article writing guidelines (text format)', null=True, verbose_name='Rules Content'),
        ),
        migrations.AlterField(
            model_name='articlerules',
            name='content_en',
            field=models.TextField(blank=True, help_text='Article writing guidelines (text format)', null=True, verbose_name='Rules Content'),
        ),
        migrations.AlterField(
            model_name='articlerules',
            name='content_ru',
            field=models.TextField(blank=True, help_text='Article writing guidelines (text format)', null=True, verbose_name='Rules Content'),
        ),
        migrations.AlterField(
            model_name='articlerules',
            name='content_uz',
            field=models.TextField(blank=True, help_text='Article writing guidelines (text format)', null=True, verbose_name='Rules Content'),
        ),
    ]
