# Generated by Django 5.2.4 on 2026-01-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_articlerules_rules_file_alter_articlerules_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='has_accepted_rules',
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biography'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='organization',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('READER', 'Reader'), ('AUTHOR', 'Author'), ('REVIEWER', 'Reviewer'), ('ADMIN', 'Administrator')], default='READER', max_length=20, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
