# Generated by Django 5.2.4 on 2026-01-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_has_accepted_rules_customuser_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_accepted_rules',
            field=models.BooleanField(default=False, verbose_name='Has Accepted Article Rules'),
        ),
    ]
