# Generated by Django 5.2.4 on 2026-01-25 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_has_accepted_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('REVIEWER_ASSIGNED', 'Reviewer Assigned'), ('ARTICLE_FOR_REVIEW', 'Article For Review'), ('REVIEW_SUBMITTED', 'Review Submitted'), ('ARTICLE_PUBLISHED', 'Article Published'), ('ARTICLE_REJECTED', 'Article Rejected'), ('CHANGES_REQUESTED', 'Changes Requested'), ('STATUS_CHANGED', 'Status Changed'), ('GENERAL', 'General')], default='GENERAL', max_length=30, verbose_name='Type')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Link')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='users_notif_user_id_1be17e_idx'), models.Index(fields=['-created_at'], name='users_notif_created_4b8aa8_idx')],
            },
        ),
    ]
