# Generated by Django 5.2.4 on 2026-01-15 09:48

import articles.models
import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Article title (max 200 characters)', max_length=200, verbose_name='Title')),
                ('title_uz', models.CharField(help_text='Article title (max 200 characters)', max_length=200, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(help_text='Article title (max 200 characters)', max_length=200, null=True, verbose_name='Title')),
                ('title_en', models.CharField(help_text='Article title (max 200 characters)', max_length=200, null=True, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from title, used in URLs', max_length=250, unique=True, verbose_name='Slug')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(help_text='Article content with rich text formatting', verbose_name='Content')),
                ('content_uz', ckeditor_uploader.fields.RichTextUploadingField(help_text='Article content with rich text formatting', null=True, verbose_name='Content')),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(help_text='Article content with rich text formatting', null=True, verbose_name='Content')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(help_text='Article content with rich text formatting', null=True, verbose_name='Content')),
                ('cover_image', models.ImageField(blank=True, help_text='Allowed formats: jpg, jpeg, png, gif, webp. Max size: 5.0MB', null=True, upload_to=articles.models.article_cover_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp']), articles.models.validate_image_size], verbose_name='Cover Image')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=10, verbose_name='Status')),
                ('views', models.PositiveIntegerField(default=0, help_text='Number of times this article has been viewed', verbose_name='Views')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-created_at'],
            },
        ),
    ]
