# Generated by Django 5.2.4 on 2026-01-23 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Keyword')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Keyword',
                'verbose_name_plural': 'Keywords',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=300, verbose_name='Title (Uzbek)')),
                ('title_ru', models.CharField(blank=True, max_length=300, verbose_name='Title (Russian)')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='Title (English)')),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('content_uz', models.TextField(verbose_name='Content (Uzbek)')),
                ('content_ru', models.TextField(blank=True, verbose_name='Content (Russian)')),
                ('content_en', models.TextField(blank=True, verbose_name='Content (English)')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_ADMIN', 'Pending Admin Review'), ('IN_REVIEW', 'In Review'), ('CHANGES_REQUESTED', 'Changes Requested'), ('REJECTED', 'Rejected'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('review_mode', models.CharField(choices=[('ALL', 'All Categories Required'), ('ANY', 'Any Category Sufficient')], default='ALL', help_text='How multi-category reviews are evaluated', max_length=10, verbose_name='Review Mode')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted At')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('admin_decision_at', models.DateTimeField(blank=True, null=True, verbose_name='Admin Decision At')),
                ('admin_note', models.TextField(blank=True, null=True, verbose_name='Admin Note')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Views')),
                ('admin_decision_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_decisions', to=settings.AUTH_USER_MODEL, verbose_name='Admin Decision By')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_ADMIN', 'Pending Admin Review'), ('IN_REVIEW', 'In Review'), ('CHANGES_REQUESTED', 'Changes Requested'), ('REJECTED', 'Rejected'), ('PUBLISHED', 'Published')], max_length=20, verbose_name='From Status')),
                ('to_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_ADMIN', 'Pending Admin Review'), ('IN_REVIEW', 'In Review'), ('CHANGES_REQUESTED', 'Changes Requested'), ('REJECTED', 'Rejected'), ('PUBLISHED', 'Published')], max_length=20, verbose_name='To Status')),
                ('reason', models.TextField(blank=True, verbose_name='Reason')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='articles.article', verbose_name='Article')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Changed By')),
            ],
            options={
                'verbose_name': 'Article Status History',
                'verbose_name_plural': 'Article Status Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100, verbose_name='Name (Uzbek)')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Name (Russian)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (English)')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewers', models.ManyToManyField(blank=True, help_text='Reviewers who can review articles in this category', limit_choices_to={'role': 'REVIEWER'}, related_name='assigned_categories', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Reviewers')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name_uz'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(help_text='Select at least one category', related_name='articles', to='articles.category', verbose_name='Categories'),
        ),
        migrations.CreateModel(
            name='CategoryPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_approvals_to_publish', models.PositiveIntegerField(default=2, help_text='Number of approval votes required', verbose_name='Minimum Approvals to Publish')),
                ('max_rejections_before_block', models.PositiveIntegerField(default=1, help_text='Article is blocked if rejections exceed this', verbose_name='Maximum Rejections Before Block')),
                ('min_required_reviews', models.PositiveIntegerField(default=2, help_text='Total reviews needed before decision', verbose_name='Minimum Required Reviews')),
                ('allow_admin_override', models.BooleanField(default=True, help_text='Admin can override policy and publish/reject directly', verbose_name='Allow Admin Override')),
                ('review_deadline_hours', models.PositiveIntegerField(blank=True, help_text='Optional deadline for reviews', null=True, verbose_name='Review Deadline (Hours)')),
                ('require_changes_comment', models.BooleanField(default=True, help_text='Reviewer must provide comment when requesting changes', verbose_name='Require Comment for Changes')),
                ('require_reject_comment', models.BooleanField(default=True, help_text='Reviewer must provide comment when rejecting', verbose_name='Require Comment for Rejection')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='articles.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Category Policy',
                'verbose_name_plural': 'Category Policies',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='articles', to='articles.keyword', verbose_name='Keywords'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('APPROVE', 'Approve'), ('CHANGES', 'Request Changes'), ('REJECT', 'Reject')], max_length=20, verbose_name='Decision')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='articles.article', verbose_name='Article')),
                ('category', models.ForeignKey(help_text='The category this review is for', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='articles.category', verbose_name='Category')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Reviewer')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-created_at'], name='articles_ar_created_312397_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status'], name='articles_ar_status_edb746_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['slug'], name='articles_ar_slug_452037_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('article', 'reviewer', 'category')},
        ),
    ]
