# Generated by Django 5.2.4 on 2026-01-26 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_file',
            field=models.FileField(blank=True, help_text='Upload article file (PDF, DOC, DOCX). Max 20MB.', null=True, upload_to='article_files/%Y/%m/', verbose_name='Article File'),
        ),
    ]
