# Generated by Django 5.2.4 on 2026-01-15 15:26

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_file',
            field=models.FileField(blank=True, help_text='Upload article as file (.txt, .doc, .docx, .pdf - max 10MB)', null=True, upload_to=articles.models.article_file_upload_path, validators=[articles.models.validate_article_file], verbose_name='Article File'),
        ),
    ]
