# Generated by Django 5.2.4 on 2026-01-30 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_fix_database_schema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('CHANGES_REQUESTED', 'Changes Requested'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='Status')),
                ('review_comment', models.TextField(blank=True, help_text='Reviewer feedback or comment', null=True, verbose_name='Review Comment')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Assigned At')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_assignments', to='articles.article', verbose_name='Article')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer_assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By')),
                ('reviewer', models.ForeignKey(limit_choices_to={'role': 'REVIEWER'}, on_delete=django.db.models.deletion.CASCADE, related_name='article_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Reviewer')),
            ],
            options={
                'verbose_name': 'Reviewer Assignment',
                'verbose_name_plural': 'Reviewer Assignments',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['article', 'status'], name='articles_re_article_d26dd6_idx'), models.Index(fields=['reviewer', 'status'], name='articles_re_reviewe_581c0f_idx')],
                'unique_together': {('article', 'reviewer')},
            },
        ),
    ]
