# Generated by Django 5.2.4 on 2026-02-26 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_remove_categories_add_publication_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='category',
            field=models.ForeignKey(blank=True, help_text='The category this review is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='articles.category', verbose_name='Category'),
        ),
    ]
